import { SourceFeedSeed } from "@/lib/domain";
import { buildFingerprint } from "@/lib/intelligence";

export const DEFAULT_SOURCE_FEEDS: SourceFeedSeed[] = [
  {
    key: "openai-news",
    label: "OpenAI News",
    kind: "rss",
    sourceType: "official_vendor",
    url: "https://openai.com/news/rss.xml",
    description: "Official OpenAI product and research announcements.",
    trustScore: 0.98,
    baseTags: ["OpenAI", "models", "API"],
    cadence: "hourly",
  },
  {
    key: "anthropic-news",
    label: "Anthropic News",
    kind: "rss",
    sourceType: "official_vendor",
    url: "https://www.anthropic.com/news/rss.xml",
    description: "Official Anthropic product and safety announcements.",
    trustScore: 0.98,
    baseTags: ["Anthropic", "Claude", "API"],
    cadence: "hourly",
  },
  {
    key: "google-ai-blog",
    label: "Google AI Blog",
    kind: "rss",
    sourceType: "official_vendor",
    url: "https://blog.google/technology/ai/rss/",
    description: "Google AI and Gemini updates.",
    trustScore: 0.95,
    baseTags: ["Google", "Gemini"],
    cadence: "daily",
  },
  {
    key: "huggingface-blog",
    label: "Hugging Face Blog",
    kind: "rss",
    sourceType: "official_blog",
    url: "https://huggingface.co/blog/feed.xml",
    description: "Open-source model tooling and transformers updates.",
    trustScore: 0.93,
    baseTags: ["Hugging Face", "Transformers", "open-source"],
    cadence: "daily",
  },
  {
    key: "latent-space",
    label: "Latent Space",
    kind: "rss",
    sourceType: "analysis_blog",
    url: "https://www.latent.space/feed",
    description: "Curated AI engineering analysis and ecosystem commentary.",
    trustScore: 0.82,
    baseTags: ["AI engineering", "ecosystem"],
    cadence: "daily",
  },
  {
    key: "the-gradient",
    label: "The Gradient",
    kind: "rss",
    sourceType: "analysis_blog",
    url: "https://thegradient.pub/rss/",
    description: "Research and applied AI coverage.",
    trustScore: 0.84,
    baseTags: ["research", "AI"],
    cadence: "daily",
  },
  {
    key: "arxiv-cs-ai",
    label: "arXiv cs.AI",
    kind: "rss",
    sourceType: "research_feed",
    url: "https://rss.arxiv.org/rss/cs.AI",
    description: "Fresh AI research papers from arXiv.",
    trustScore: 0.9,
    baseTags: ["research", "papers"],
    cadence: "daily",
  },
  {
    key: "two-minute-papers",
    label: "Two Minute Papers",
    kind: "rss",
    sourceType: "youtube_feed",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCbfYPyITQ-7l4upoX8nvctg",
    description: "Video explainers for notable AI research and demos.",
    trustScore: 0.76,
    baseTags: ["videos", "research"],
    cadence: "daily",
  },
  {
    key: "openai-node-releases",
    label: "openai/openai-node Releases",
    kind: "github_releases",
    sourceType: "github_release",
    repoFullName: "openai/openai-node",
    description: "Official OpenAI Node SDK releases.",
    trustScore: 0.97,
    baseTags: ["OpenAI", "TypeScript", "SDK"],
    cadence: "hourly",
  },
  {
    key: "vercel-ai-releases",
    label: "vercel/ai Releases",
    kind: "github_releases",
    sourceType: "github_release",
    repoFullName: "vercel/ai",
    description: "Vercel AI SDK releases for app developers.",
    trustScore: 0.95,
    baseTags: ["Vercel AI SDK", "TypeScript", "React"],
    cadence: "hourly",
  },
  {
    key: "langchainjs-releases",
    label: "langchainjs Releases",
    kind: "github_releases",
    sourceType: "github_release",
    repoFullName: "langchain-ai/langchainjs",
    description: "LangChain JS release activity.",
    trustScore: 0.92,
    baseTags: ["LangChain", "TypeScript"],
    cadence: "hourly",
  },
  {
    key: "transformers-releases",
    label: "transformers Releases",
    kind: "github_releases",
    sourceType: "github_release",
    repoFullName: "huggingface/transformers",
    description: "Transformers release activity and changelog.",
    trustScore: 0.95,
    baseTags: ["Transformers", "Python"],
    cadence: "hourly",
  },
  {
    key: "copilot-releases",
    label: "GitHub Copilot Releases",
    kind: "github_releases",
    sourceType: "github_release",
    repoFullName: "microsoft/vscode-copilot-release",
    description: "GitHub Copilot extension release activity.",
    trustScore: 0.94,
    baseTags: ["GitHub Copilot", "VS Code"],
    cadence: "hourly",
  },
];

export const DEMO_FALLBACK_ITEMS = [
  {
    title: "OpenAI expands coding model controls for tool calling and long-context workflows",
    url: "https://example.com/demo/openai-coding-model-controls",
    summary:
      "A seeded fallback item showing how official model updates can affect developer tooling, agent design, and IDE assistants.",
    sourceName: "Demo Feed",
    sourceType: "seeded_demo",
    tags: ["OpenAI", "API", "Agents", "TypeScript"],
  },
  {
    title: "Vercel AI SDK release improves structured output and provider routing",
    url: "https://example.com/demo/vercel-ai-sdk-release",
    summary:
      "A seeded fallback item representing a stack-specific release that should rank highly for web developers building AI products.",
    sourceName: "Demo Feed",
    sourceType: "seeded_demo",
    tags: ["Vercel AI SDK", "React", "Next.js", "TypeScript"],
  },
  {
    title: "New benchmark compares frontier coding models on real repository tasks",
    url: "https://example.com/demo/coding-model-benchmark",
    summary:
      "A seeded benchmark-style item for evaluating model choice, latency, and cost tradeoffs.",
    sourceName: "Demo Feed",
    sourceType: "seeded_demo",
    tags: ["Benchmarks", "OpenAI", "Anthropic", "GitHub Copilot"],
  },
];

export function demoItemKey(title: string, url: string) {
  return buildFingerprint("demo", title, url);
}
